# Generated by Django 6.1.1 on 2026-09-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='awaiting_approval',
            field=models.BooleanField(default=False),
        ),
    ]
